<template>
  <fieldset>
    <legend>News search</legend>
    <p>
      You can specify a date range to narrow down the search for news articles.
    </p>
    <div class="flexbox">
      <div class="col">
        <label for="startRange">
          <code> From {{ asset.dates[range[0]] }} </code>
        </label>
        <input
          type="range"
          min="0"
          :max="range[1]"
          v-model="range[0]"
          class="slider"
          id="startRange"
        />
      </div>
      <div class="col">
        <label class="col" for="endRange"
          ><code>To {{ asset.dates[range[1]] }}</code></label
        >
        <input
          type="range"
          :min="range[0]"
          :max="asset.dates.length - 1"
          v-model="range[1]"
          class="slider"
          id="endRange"
        />
      </div>
    </div>
    <button :class="{ shake: shake }" @click="getNews()">
      <span v-if="searching">Searching...</span>
      <span v-else>🔍 Check</span>
    </button>
    <template v-if="asset.news.length > 0">
      <br />
      <article v-for="(item, idx) of asset.news" :key="idx">
        <div>{{ item.datetime }}</div>
        <a :href="item.url" target="_blank">{{ item.headline }}</a>
        <div>{{ item.summary }}</div>
        <hr v-if="idx + 1 < asset.news.length" :key="'hr-' + idx" />
      </article>
    </template>
  </fieldset>
</template>

<script>
import { useAPI } from "../composables/use-api";
import { asset } from "../composables/use-store";
import { ref, computed, onMounted } from "vue";

export default {
  setup() {
    const range = ref([0, asset.dates.length - 1]);
    const shake = ref(false);
    const searching = ref(false);

    const getNews = async () => {
      shake.value = false;
      searching.value = true;
      const from = asset.dates[range.value[0]];
      const to = asset.dates[range.value[1]];
      await useAPI.requestHandler("news", {
        asset: asset,
        from: from,
        to: to,
      });
      searching.value = false;
      // animate the search button to indicate that no news were found
      if (asset.news.length === 0) shake.value = true;
    };

    return {
      asset,
      range,
      getNews,
      searching,
      shake,
    };
  },
};
</script>

<!-- Add "scoped" keyibute to limit CSS to this component only -->
<style scoped>
article,
label {
  font-size: 10pt;
}

hr {
  margin: 5px 0 10px 0;
}

.shake {
  animation: shake-horizontal 0.8s cubic-bezier(0.455, 0.03, 0.515, 0.955) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2020-6-3 1:1:49
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation shake-horizontal
 * ----------------------------------------
 */
@keyframes shake-horizontal {
  0%,
  100% {
    transform: translateX(0);
  }
  10%,
  30%,
  50%,
  70% {
    transform: translateX(-10px);
  }
  20%,
  40%,
  60% {
    transform: translateX(10px);
  }
  80% {
    transform: translateX(8px);
  }
  90% {
    transform: translateX(-8px);
  }
}
</style>
