<template>
  <details>
    <summary><span class="link">News</span></summary>
    <fieldset>
      <legend>News search</legend>
      <p>
        You can specify a date range to narrow down the search for news
        articles.
      </p>
      <label for="startRange">
        <code> From {{ from }} </code>
      </label>
      <input
        type="range"
        min="0"
        :max="range[1]"
        v-model="range[0]"
        class="slider"
        id="startRange"
      />
      <label class="col" for="endRange"
        ><code>To {{ to }}</code></label
      >
      <input
        type="range"
        :min="range[0]"
        :max="asset.dates.length - 1"
        v-model="range[1]"
        class="slider"
        id="endRange"
      />
      <button :class="{ shake: shake }" @click="searchNews()">
        <span v-if="searching">Searching...</span>
        <span v-else>🔍 Check</span>
      </button>
      <template v-if="asset.dataload.news.length > 0">
        <br />
        <article v-for="(item, idx) of asset.dataload.news" :key="idx">
          <div>{{ item.datetime }}</div>
          <a :href="item.url" target="_blank">{{ item.headline }}</a>
          <div>{{ item.summary }}</div>
          <hr v-if="idx + 1 < asset.dataload.news.length" :key="'hr-' + idx" />
        </article>
      </template>
    </fieldset>
  </details>
</template>

<script setup>
import { defineProps, ref, computed, onMounted, watch } from "vue";
import useNewsApi from "../composables/useNewsApi";

const props = defineProps({
  asset: Object,
});
const range = ref([0, props.asset.dates.length - 1]);
const shake = ref(false);
const searching = ref(false);
const from = computed(() => props.asset.dates[range.value[0]]);
const to = computed(() => props.asset.dates[range.value[1]]);
props.asset.dataload.news = [];

const { getNews } = useNewsApi(props.asset);

const searchNews = async () => {
  shake.value = false;
  searching.value = true;
  console.log("Search news from: ", from.value);
  console.log("Search news to: ", to.value);
  await getNews(from.value, to.value);
  searching.value = false;
  // animate the search button to indicate that no news were found
  if (props.asset.dataload.news.length === 0) shake.value = true;
};
</script>

<!-- Add "scoped" keyibute to limit CSS to this component only -->
<style scoped>
button {
  margin: 10px 0;
  display: block;
}

article,
label {
  font-size: 10pt;
}

hr {
  margin: 5px 0 10px 0;
}

.shake {
  animation: shake-horizontal 0.8s cubic-bezier(0.455, 0.03, 0.515, 0.955) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2020-6-3 1:1:49
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation shake-horizontal
 * ----------------------------------------
 */
@keyframes shake-horizontal {
  0%,
  100% {
    transform: translateX(0);
  }
  10%,
  30%,
  50%,
  70% {
    transform: translateX(-10px);
  }
  20%,
  40%,
  60% {
    transform: translateX(10px);
  }
  80% {
    transform: translateX(8px);
  }
  90% {
    transform: translateX(-8px);
  }
}
</style>
